name: Deploy Post Service

on:
  push:
    branches:
      - main
      - check-api-gateway-token-validation
    paths:
      - 'services/post-service/**'
      - '.github/workflows/deploy-post-service.yml'
  workflow_dispatch:
  workflow_run:
    workflows:
      - publish-shared
    types:
      - completed

env:
  PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  SERVICE_NAME: post-service
  REGION: ${{ vars.REGION }}
  WORKLOAD_IDENTITY_PROVIDER: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
  DEPLOYMENT_SERVICE_ACCOUNT: ${{ vars.DEPLOYMENT_SERVICE_ACCOUNT }}
  IS_AUTHENTICATED_VIA_AUTH_GATEWAY: true
  FIRESTORE_DATABASE_NAME: ${{ vars.FIRESTORE_DATABASE_NAME }}


jobs:
  deploy-dev:
    name: Build and Deploy Post Service to dev
    runs-on: ubuntu-latest
    environment: 
      name: dev
    permissions:
      contents: read
      packages: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: check-api-gateway-token-validation

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.DEPLOYMENT_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" > github_token.txt
          docker build --secret id=github_token,src=github_token.txt -f services/${{ env.SERVICE_NAME }}/Dockerfile -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker tag gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest
          rm github_token.txt

      - name: Push Docker image to GCR
        run: |
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --no-allow-unauthenticated \
            --memory 512Mi \
            --cpu 1 \
            --max-instances 3 \
            --min-instances 0 \
            --timeout 300 \
            --port 8080 \
            --ingress all \
            --set-env-vars "FIREBASE_PROJECT_ID=${{ env.PROJECT_ID }},DATABASE_NAME=${{ env.FIRESTORE_DATABASE_NAME }},USER_SERVICE_URL=${{vars.USER_SERVICE_URL}}"

      - name: Show deployment URL
        run: |
          echo "Deployment successful!"
          gcloud run services describe ${{ env.SERVICE_NAME }} \
            --region ${{ env.REGION }} \
            --format 'value(status.url)'

